name: ohmygiraffe
adopt-info: ohmygiraffe
summary: ohmygiraffe
description: |
  A delightful game of survival

base: core24
grade: stable
confinement: strict
license: Proprietary
website: http://www.ohmygiraffe.com
source-code: https://github.com/kz6fittycent/ohmygiraffe
issues: https://github.com/kz6fittycent/ohmygiraffe
icon: snap/gui/ohmygiraffe.png

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  ohmygiraffe:
    extensions:
      - gnome
    command: "usr/bin/love-0.9 $SNAP/usr/bin/oh-my-giraffe.love"
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_ON/pulseaudio:$SNAP"    
    plugs: 
      - audio-playback
      - x11
      - opengl
      - unity7
      
parts:
  ohmygiraffe:
    source: https://github.com/kz6fittycent/ohmygiraffe
    source-type: git
    plugin: nil
    
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)" 
    
    override-build: |
      mkdir -p BUILD
      cd BUILD
      
      # Grab oh-my-giraffe
      wget "http://www.ohmygiraffe.com/static/releases/oh-my-giraffe.love"
      mkdir -p $CRAFT_PART_INSTALL/usr/bin/
      cp oh-my-giraffe.love $CRAFT_PART_INSTALL/usr/bin/
      
    build-packages:
      - wget

    stage-packages:
      - freeglut3-dev
      - libgl1-mesa-dri
      - libglew2.2
      - lua-socket
      - libluajit-5.1-2
      - libsdl2-2.0-0
      - libopenal1
      - libilmbase-dev
      - libdevil1c2
      - libogg0
      - libmpg123-0
      - libtheora0
      - libvorbisfile3
      - libmodplug1
      - libphysfs1

  love:
    plugin: dump
    source: https://github.com/love2d/love/releases/download/0.9.0/love_0.9.0_amd64.deb
    
  liblove:
    plugin: dump
    source: https://github.com/love2d/love/releases/download/0.9.0/liblove_0.9.0_amd64.deb      
