name: ohmygiraffe
adopt-info: ohmygiraffe
summary: ohmygiraffe
description: |
  A delightful game of survival

base: core18
grade: stable
confinement: strict
license: Proprietary

architectures:
  - build-on: amd64

apps:
  ohmygiraffe:
    extensions:
      - gnome-3-34
    command: "usr/bin/love-0.9 $SNAP/usr/bin/oh-my-giraffe.love"
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP"    
    plugs: 
      - audio-playback
      - x11
      - opengl
      - unity7
      
parts:
  ohmygiraffe:
    source: https://github.com/kz6fittycent/ohmygiraffe
    source-type: git
    plugin: nil
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
    
    override-build: |
      mkdir -p BUILD
      cd BUILD
      
      # Grab oh-my-giraffe
      wget "http://www.ohmygiraffe.com/static/releases/oh-my-giraffe.love"
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin/
      cp oh-my-giraffe.love $SNAPCRAFT_PART_INSTALL/usr/bin/
      
    build-packages:
      - wget

    stage-packages:
      - freeglut3
      - love
